/**
 * Händler-Keywords (AT / DACH / EU) – normalisiert ohne Akzente.
 * Reihenfolge = Priorität (spezifisch zuerst).
 */
const RULE_GROUPS = [
  {
    category: "Versicherung",
    icon: "green",
    keywords: [
      "versicherung",
      "zurich",
      "uniqa",
      "generali versicherung",
      "allianz",
      "ergo",
      "wiener staedtische",
      "grawe",
      "donavers",
      "merkur versicherung",
      "insurance",
    ],
  },
  {
    category: "Haustiere",
    icon: "pink",
    keywords: [
      "fressnapf",
      "futterhaus",
      "das futterhaus",
      "tierplus",
      "zooshop",
      "kolle zoo",
      "vetklinik",
      "tierarzt",
      "kleintier",
      "hundefutter",
      "zoofach",
    ],
  },
  {
    category: "Gesundheit",
    icon: "teal",
    keywords: [
      "apotheke",
      "apothekerei",
      "benu",
      "pharmacy",
      "gesundheit",
      "krankenhaus",
      "klinik",
      "arztpraxis",
      "ordination",
      "labor",
      "medizin",
      "optiker",
      "specsavers",
      "hearing",
    ],
  },
  {
    category: "Auto / Tanken",
    icon: "red",
    keywords: [
      "arboe",
      "arbö",
      "oeamtc",
      "ace auto",
      "adac",
      "tuev",
      "ueberpruefung",
      "asfinag",
      "maut",
      "vignette",
      "strassenmeisterei",
      "aral",
      "shell",
      "omv",
      "jet tank",
      "avia",
      "eni ",
      "total energie",
      "bp tank",
      "turmoel",
      "turmöl",
      "diskont tank",
      "beste tank",
      "socar",
      "tankstelle",
      "tankst",
      "parkenplus",
      "parken plus",
      "apcoa",
      "contipark",
      "parkhaus",
      "parkplatz",
      "parkticket",
      "garage park",
      "car wash",
      "waschanlage",
      "atu ",
      "euromaster",
      "reifen",
      "autohaus",
      "werkstatt",
      "kfz",
      "carglass",
      "pitstop",
      "avis",
      "europcar",
      "sixt",
      "hertz",
      "carvertical",
    ],
  },
  {
    category: "Mobilität",
    icon: "yellow",
    keywords: [
      "oebb",
      "öbb",
      "westbahn",
      "wiener linien",
      "verkehrsverbund",
      "wiener lokalbahn",
      "svv",
      "vvk",
      "vvt",
      "salzburg ag",
      "postbus",
      "flixbus",
      "flix train",
      "deutsche bahn",
      "db vertrieb",
      "obb",
      "schenker",
      "uber",
      "bolt.eu",
      "free now",
      "freenow",
      "kapten",
      "taxi",
      "flughafen",
      "bahnhof",
      "hauptbahnhof",
      "westbahnhof",
      "wiener neustadt hbf",
      "blablacar",
      "lime ",
      "tier scooter",
      "voestalpine bahn",
    ],
  },
  {
    category: "Abos",
    icon: "teal",
    keywords: [
      "netflix",
      "spotify",
      "disney plus",
      "amazon prime",
      "apple.com bill",
      "apple.com/bill",
      "google storage",
      "google one",
      "youtube premium",
      "cursor",
      "adobe",
      "microsoft",
      "office 365",
      "github",
      "dropbox",
      "icloud",
      "playstation network",
      "xbox",
      "steam",
      "nintendo",
      "deezer",
      "audible",
      "onlyfans",
      "openai",
      "chatgpt",
      "notion",
      "canva",
      "linkedin premium",
      "a1 telekom",
      "magenta",
      "drei ",
      "hot telecom",
      "salzburg ag telecom",
      "internet service",
      "domain",
      "hosting",
      "strato",
      "ionos",
    ],
  },
  {
    category: "Essen",
    icon: "purple",
    keywords: [
      "mcdonald",
      "burger king",
      "kfc",
      "subway",
      "vapiano",
      "losteria",
      "swing kitchen",
      "wienerwald",
      "nordsee",
      "schnitzel",
      "pizzeria",
      "restaurant",
      "gasthaus",
      "heuriger",
      "cafe",
      "kaffee",
      "starbucks",
      "coffee",
      "billa",
      "spar ",
      "spar dankt",
      "hofer",
      "lidl",
      "penny",
      "merkur",
      "unimarkt",
      "nah und frisch",
      "rewe",
      "globus",
      "gourmet",
      "gms gourmet",
      "mpreis",
      "interspar",
      "eurospar",
      "sutterlüty",
      "sutterluety",
      "keusche",
      "nahfrisch",
      "backwerk",
      "anker",
      "der mann",
      "konditorei",
      "baeckerei",
      "bäckerei",
      "lieferando",
      "mjam",
      "wolt",
      "foodora",
      "dominos",
      "pizza hut",
      "thali",
      "sush",
      "kebab",
      "döner",
      "doner",
      "coca cola",
      "red bull",
      "safran",
      "kaisers",
      "knödel",
      "xalos",
      "safran",
    ],
  },
  {
    category: "Einkaufen",
    icon: "purple",
    keywords: [
      "dm fil",
      "dm-fil",
      "dm drogerie",
      "mueller",
      "müller",
      "bipa",
      "douglas",
      "parfumerie",
      "ikea",
      "mömax",
      "momax",
      "hornbach",
      "obi ",
      "bauhaus",
      "baumax",
      "kika",
      "xxxlutz",
      "poco",
      "depot",
      "zara",
      "h&m",
      "c&a",
      "primark",
      "deichmann",
      "paylife",
      "mediamarkt",
      "media markt",
      "saturn",
      "expert",
      "electronic",
      "libro",
      "thalia",
      "amazon",
      "zalando",
      "shein",
      "temu",
      "action ",
      "tedi",
      "kik ",
      "new yorker",
      "rituals",
      "cosmetics",
      "hellofresh",
      "helloly",
    ],
  },
  {
    category: "Freizeit",
    icon: "pink",
    keywords: [
      "kino",
      "cineplexx",
      "burg kino",
      "theater",
      "stadthalle",
      "arena wien",
      "konzerthaus",
      "musical",
      "ticketmaster",
      "oeticket",
      "eventim",
      "fitness",
      "mcfit",
      "holmes place",
      "fitinn",
      "wellpass",
      "therme",
      "badeteich",
      "schwimmbad",
      "museum",
      "zoo ",
      "prater",
      "bowling",
      "escape room",
      "gamestop",
      "steam purchase",
    ],
  },
  {
    category: "Wohnen",
    icon: "green",
    keywords: [
      "miete",
      "hausverwaltung",
      "wohnbau",
      "gemeinde",
      "finanzamt",
      "stadt wien",
      "magistrat",
      "strom",
      "gas ",
      "energie",
      "wien energie",
      "verbund",
      "awg",
      "kanal",
      "abfall",
      "immobilien",
    ],
  },
];

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function matchesKeyword(normalized, keyword) {
  const k = keyword
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/ß/g, "ss")
    .trim();
  if (!k) return false;
  if (k.length <= 4) {
    return new RegExp(`\\b${escapeRegex(k)}\\b`).test(normalized);
  }
  return normalized.includes(k);
}

function matchKeywordRules(normalized) {
  for (const group of RULE_GROUPS) {
    for (const keyword of group.keywords) {
      if (matchesKeyword(normalized, keyword)) {
        return { category: group.category, icon: group.icon, source: "keyword" };
      }
    }
  }
  return null;
}

module.exports = { RULE_GROUPS, matchKeywordRules, matchesKeyword };
